%% Calculating Specs
sserror = mean(abs(out.error(2000:2500, 2))); %Steady State Error
effort = sum((out.pidsteer(1:2000)).^2); %Controller Effort
overshoot = (max(out.output) - 1); %Maximum Percentage Overshoot

%% Plotting Bode Plot
num = [0 0.0745802180712488 -0.0678509105996389]; 
den = [1 -2.37963452375578 1.95832042342380 -0.717217509691274 0.138531614834883]; 
car = tf(num, den, 1); 

%PID Constants generated by Root Locus
Kp = 1.12924229948271;
Ki = 0.0270272495971814;
Kd = 1.88301790267392;
a1 = -1;
b0 = Kp + Ki + Kd; 
b1 = -(Kp+2*Kd); 
b2 = Kd; 
num2 = [b0 b1 b2]; 
den2 = [1 -1]; 
C = tf(num2, den2, 1); 

sys = car * C; 
sys2 = feedback(sys, 1); 
margin(sys2); 